### PR TITLE
🐛 修复因chatgpt更新造成的cf cookies获取失败

### PR DESCRIPTION
**Pull request by CCYellowStar**
### 这个 PR 带来了什么样的更改？

- [x] 错误修复
- [ ] 新功能 
- [ ] 文档/注释
- [ ] 代码格式
- [ ] 代码重构
- [ ] 测试用例
- [ ] 性能优化
- [ ] 外观样式
- [ ] 项目构建
- [ ] 依赖环境
- [ ] 持续集成/部署
- [ ] 其他，请描述:

### 这个 PR 是否存在破坏性变更？

- [ ] 是的，并已在 issue #___ 号中获得批准
- [x] 没有

### 描述

修复因chatgpt更新造成的cf cookies获取失败
包括那个cf验证

### 动机和背景

#119   （也许）

### 检查工作

- [ ] 我对我的代码进行了注释，特别是在难以理解的部分
- [ ] 我的更改需要更新文档，并且已对文档进行了相应的更改
- [x] 我添加了测试并且已经在本地通过，以证明我的修复补丁或新功能有效
- [x] 我已检查并确保更改没有与其他打开的 [Pull Requests](../pulls) 重复

### CODE REVIEW

**Comment by CCYellowStar** [comment]
> 更新了chatgpt.py，发现服务器Ubuntu环境下运行还是报错“cf cookies获取失败”；本地机Windows环境下运行正常，没有报错。。。

https://github.com/A-kirami/nonebot-plugin-chatgpt/issues/114#issuecomment-1429825457
试试打开这个看看卡在哪了

**Comment by CounterpickToWin** [comment]
> > 更新了chatgpt.py，发现服务器Ubuntu环境下运行还是报错“cf cookies获取失败”；本地机Windows环境下运行正常，没有报错。。。
> 
> [#114 (comment)](https://github.com/A-kirami/nonebot-plugin-chatgpt/issues/114#issuecomment-1429825457) 试试打开这个看看卡在哪了

改了以后报错如下，我应该是安装了playwright，服务器上可以配置所谓的display enviroment么。。。不是很懂，大佬求助

02-18 00:09:10 [ERROR] nonebot_plugin_chatgpt | playwright未安装，请先在shell中运行playwright install
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/root/first/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "/root/first/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 187, in run
    uvicorn.run(
  File "/root/first/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 569, in run
    server.run()
  File "/root/first/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/first/.venv/lib/python3.10/site-packages/nonebot/message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
  File "/root/first/.venv/lib/python3.10/site-packages/nonebot/message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/first/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 732, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/first/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 707, in simple_run
    await handler(
  File "/root/first/.venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/first/.venv/lib/python3.10/site-packages/nonebot_plugin_chatgpt/__init__.py", line 60, in ai_chat
    await chat_bot.playwright_start()
> File "/root/first/.venv/lib/python3.10/site-packages/nonebot_plugin_chatgpt/chatgpt.py", line 54, in playwright_start
    self.browser = await playwright.firefox.launch(
  File "/root/first/.venv/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 14340, in launch
    await self._impl_obj.launch(
  File "/root/first/.venv/lib/python3.10/site-packages/playwright/_impl/_browser_type.py", line 93, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "/root/first/.venv/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
  File "/root/first/.venv/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 419, in wrap_api_call
    return await cb()
  File "/root/first/.venv/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: 
╔════════════════════════════════════════════════════════════════════════════════════════════════╗
║ Looks like you launched a headed browser without having a XServer running.                     ║
║ Set either 'headless: true' or use 'xvfb-run <your-playwright-app>' before running Playwright. ║
║                                                                                                ║
║ <3 Playwright Team                                                                             ║
╚════════════════════════════════════════════════════════════════════════════════════════════════╝
=========================== logs ===========================
<launching> /root/.cache/ms-playwright/firefox-1372/firefox/firefox -no-remote -wait-for-browser -foreground -profile /tmp/playwright_firefoxdev_profile-WvpOOu -juggler-pipe -silent
<launched> pid=50416
[pid=50416][err] Error: no DISPLAY environment variable specified
[pid=50416] <process did exit: exitCode=1, signal=null>
[pid=50416] starting temporary directories cleanup

**Comment by CCYellowStar** [comment]
> > > 更新了chatgpt.py，发现服务器Ubuntu环境下运行还是报错“cf cookies获取失败”；本地机Windows环境下运行正常，没有报错。。。
> > 
> > 
> > [#114 (comment)](https://github.com/A-kirami/nonebot-plugin-chatgpt/issues/114#issuecomment-1429825457) 试试打开这个看看卡在哪了
> 
> 改了以后报错如下，我应该是安装了playwright，服务器上可以配置所谓的display enviroment么。。。不是很懂，大佬求助
> 
> 02-18 00:09:10 [ERROR] nonebot_plugin_chatgpt | playwright未安装，请先在shell中运行playwright install Traceback (most recent call last): File "", line 17, in File "/root/first/.venv/lib/python3.10/site-packages/nonebot/**init**.py", line 273, in run get_driver().run(*args, **kwargs) File "/root/first/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 187, in run uvicorn.run( File "/root/first/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 569, in run server.run() File "/root/first/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run return asyncio.run(self.serve(sockets=sockets)) File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run return loop.run_until_complete(main) File "/root/first/.venv/lib/python3.10/site-packages/nonebot/message.py", line 141, in _check_matcher await _run_matcher(Matcher, bot, event, state, stack, dependency_cache) File "/root/first/.venv/lib/python3.10/site-packages/nonebot/message.py", line 187, in _run_matcher await matcher.run(bot, event, state, stack, dependency_cache) File "/root/first/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 732, in run await self.simple_run(bot, event, state, stack, dependency_cache) File "/root/first/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 707, in simple_run await handler( File "/root/first/.venv/lib/python3.10/site-packages/nonebot/dependencies/**init**.py", line 108, in **call** return await cast(Callable[..., Awaitable[R]], self.call)(**values) File "/root/first/.venv/lib/python3.10/site-packages/nonebot_plugin_chatgpt/**init**.py", line 60, in ai_chat await chat_bot.playwright_start()
> 
> > File "/root/first/.venv/lib/python3.10/site-packages/nonebot_plugin_chatgpt/chatgpt.py", line 54, in playwright_start
> > self.browser = await playwright.firefox.launch(
> > File "/root/first/.venv/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 14340, in launch
> > await self._impl_obj.launch(
> > File "/root/first/.venv/lib/python3.10/site-packages/playwright/_impl/_browser_type.py", line 93, in launch
> > Browser, from_channel(await self._channel.send("launch", params))
> > File "/root/first/.venv/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 44, in send
> > return await self._connection.wrap_api_call(
> > File "/root/first/.venv/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 419, in wrap_api_call
> > return await cb()
> > File "/root/first/.venv/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 79, in inner_send
> > result = next(iter(done)).result()
> > playwright._impl._api_types.Error:
> > ╔════════════════════════════════════════════════════════════════════════════════════════════════╗
> > ║ Looks like you launched a headed browser without having a XServer running.                     ║
> > ║ Set either 'headless: true' or use 'xvfb-run ' before running Playwright. ║
> > ║                                                                                                ║
> > ║ <3 Playwright Team                                                                             ║
> > ╚════════════════════════════════════════════════════════════════════════════════════════════════╝
> > =========================== logs ===========================
> >  /root/.cache/ms-playwright/firefox-1372/firefox/firefox -no-remote -wait-for-browser -foreground -profile /tmp/playwright_firefoxdev_profile-WvpOOu -juggler-pipe -silent
> >  pid=50416
> > [pid=50416][err] Error: no DISPLAY environment variable specified
> > [pid=50416] 
> > [pid=50416] starting temporary directories cleanup

你的服务器应该有gui的吧，我没有Ubuntu我也不太清楚

**Comment by CCYellowStar** [comment]
你可以在playwright项目的issue找找

> > > > > 更新了chatgpt.py，发现服务器Ubuntu环境下运行还是报错“cf cookies获取失败”；本地机Windows环境下运行正常，没有报错。。。
> > > > 
> > > > 
> > > > [#114 (comment)](https://github.com/A-kirami/nonebot-plugin-chatgpt/issues/114#issuecomment-1429825457) 试试打开这个看看卡在哪了
> > > 
> > > 
> > > 改了以后报错如下，我应该是安装了playwright，服务器上可以配置所谓的display enviroment么。。。不是很懂，大佬求助
> > > 02-18 00:09:10 [ERROR] nonebot_plugin_chatgpt | playwright未安装，请先在shell中运行playwright install Traceback (most recent call last): File "", line 17, in File "/root/first/.venv/lib/python3.10/site-packages/nonebot/**init**.py", line 273, in run get_driver().run(*args, **kwargs) File "/root/first/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 187, in run uvicorn.run( File "/root/first/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 569, in run server.run() File "/root/first/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run return asyncio.run(self.serve(sockets=sockets)) File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run return loop.run_until_complete(main) File "/root/first/.venv/lib/python3.10/site-packages/nonebot/message.py", line 141, in _check_matcher await _run_matcher(Matcher, bot, event, state, stack, dependency_cache) File "/root/first/.venv/lib/python3.10/site-packages/nonebot/message.py", line 187, in _run_matcher await matcher.run(bot, event, state, stack, dependency_cache) File "/root/first/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 732, in run await self.simple_run(bot, event, state, stack, dependency_cache) File "/root/first/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 707, in simple_run await handler( File "/root/first/.venv/lib/python3.10/site-packages/nonebot/dependencies/**init**.py", line 108, in **call** return await cast(Callable[..., Awaitable[R]], self.call)(**values) File "/root/first/.venv/lib/python3.10/site-packages/nonebot_plugin_chatgpt/**init**.py", line 60, in ai_chat await chat_bot.playwright_start()
> > > > File "/root/first/.venv/lib/python3.10/site-packages/nonebot_plugin_chatgpt/chatgpt.py", line 54, in playwright_start
> > > > self.browser = await playwright.firefox.launch(
> > > > File "/root/first/.venv/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 14340, in launch
> > > > await self._impl_obj.launch(
> > > > File "/root/first/.venv/lib/python3.10/site-packages/playwright/_impl/_browser_type.py", line 93, in launch
> > > > Browser, from_channel(await self._channel.send("launch", params))
> > > > File "/root/first/.venv/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 44, in send
> > > > return await self._connection.wrap_api_call(
> > > > File "/root/first/.venv/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 419, in wrap_api_call
> > > > return await cb()
> > > > File "/root/first/.venv/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 79, in inner_send
> > > > result = next(iter(done)).result()
> > > > playwright._impl._api_types.Error:
> > > > ╔════════════════════════════════════════════════════════════════════════════════════════════════╗
> > > > ║ Looks like you launched a headed browser without having a XServer running.                     ║
> > > > ║ Set either 'headless: true' or use 'xvfb-run ' before running Playwright. ║
> > > > ║                                                                                                ║
> > > > ║ <3 Playwright Team                                                                             ║
> > > > ╚════════════════════════════════════════════════════════════════════════════════════════════════╝
> > > > =========================== logs ===========================
> > > > /root/.cache/ms-playwright/firefox-1372/firefox/firefox -no-remote -wait-for-browser -foreground -profile /tmp/playwright_firefoxdev_profile-WvpOOu -juggler-pipe -silent
> > > > pid=50416
> > > > [pid=50416][err] Error: no DISPLAY environment variable specified
> > > > [pid=50416]
> > > > [pid=50416] starting temporary directories cleanup
> > 
> > 
> > 你的服务器应该有gui的吧，我没有Ubuntu我也不太清楚
> 
> 我再研究研究 谢谢

**Comment by zxczaq001** [comment]
> > 更新了chatgpt.py，发现服务器Ubuntu环境下运行还是报错“cf cookies获取失败”；本地机Windows环境下运行正常，没有报错。。。
> 
> [#114 (comment)](https://github.com/A-kirami/nonebot-plugin-chatgpt/issues/114#issuecomment-1429825457) 试试打开这个看看卡在哪了

image
我的debian11也是 playwright我也是安装过的

**Comment by CCYellowStar** [comment]
主要是我怀疑现在Ubuntu验证界面可能不一样，但是不关闭headless看看，也不知道是什么

**Comment by zxczaq001** [comment]
image
我用xvfb-run nb run运行之后虽然还是会报错但是正常返回了..

**Comment by CCYellowStar** [comment]
现在你运行的时候不是可以看到浏览器了吗，看看浏览器在人机验证那里正常吗

**Comment by zxczaq001** [comment]
浏览器的日志在哪看..

**Comment by CCYellowStar** [comment]
> 浏览器的日志在哪看..

你把headless改成false的时候不是使用插件都会自动打开浏览器吗

**Comment by zxczaq001** [comment]
> 

额 没有 我debian没有图形化界面

**Comment by CCYellowStar** [comment]
> > 
> 
> 额 没有 我debian没有图形化界面

那你现在有没有更新了我pr的chatgpt.py

**Comment by CounterpickToWin** [comment]
> 主要是我怀疑现在Ubuntu验证界面可能不一样，但是不关闭headless看看，也不知道是什么

我也觉得是验证界面不一样，但我们用的linux云服务器默认不带gui的，只有命令行，要用的话还要另外再装，而且运行gui比较耗资源。我有空在本地虚拟机上配置下linux环境然后再测试一下好了，看看是浏览器哪一步出问题

**Comment by CCYellowStar** [comment]
> > 主要是我怀疑现在Ubuntu验证界面可能不一样，但是不关闭headless看看，也不知道是什么
> 
> 我也觉得是验证界面不一样，但我们用的linux云服务器默认不带gui的，只有命令行，要用的话还要另外再装，而且运行gui比较耗资源。我有空在本地虚拟机上配置下linux环境然后再测试一下好了，看看是浏览器哪一步出问题

你上面那个人xvfb-run nb run之后好像误打误撞的能用了，虽然还是有报错

**Comment by zxczaq001** [comment]
> 



> > > 主要是我怀疑现在Ubuntu验证界面可能不一样，但是不关闭headless看看，也不知道是什么
> > 
> > 
> > 我也觉得是验证界面不一样，但我们用的linux云服务器默认不带gui的，只有命令行，要用的话还要另外再装，而且运行gui比较耗资源。我有空在本地虚拟机上配置下linux环境然后再测试一下好了，看看是浏览器哪一步出问题
> 
> 你上面那个人xvfb-run nb run之后好像误打误撞的能用了，虽然还是有报错

我试了一下你修改的chatgpt.py 正常nb run运行会报错 但是用xvfb-run nb run没报错

**Comment by CCYellowStar** [comment]
> > 
> 
> 
> 
> > > > 主要是我怀疑现在Ubuntu验证界面可能不一样，但是不关闭headless看看，也不知道是什么
> > > 
> > > 
> > > 我也觉得是验证界面不一样，但我们用的linux云服务器默认不带gui的，只有命令行，要用的话还要另外再装，而且运行gui比较耗资源。我有空在本地虚拟机上配置下linux环境然后再测试一下好了，看看是浏览器哪一步出问题
> > 
> > 你上面那个人xvfb-run nb run之后好像误打误撞的能用了，虽然还是有报错
> 
> 我试了一下你修改的chatgpt.py 正常nb run运行会报错 但是用xvfb-run nb run没报错

我这个pr就是修报错但是能运行的，反正在Windows是正常的

**Comment by CounterpickToWin** [comment]
> > > 
> > 
> > 
> > > > > 主要是我怀疑现在Ubuntu验证界面可能不一样，但是不关闭headless看看，也不知道是什么
> > > > 
> > > > 
> > > > 我也觉得是验证界面不一样，但我们用的linux云服务器默认不带gui的，只有命令行，要用的话还要另外再装，而且运行gui比较耗资源。我有空在本地虚拟机上配置下linux环境然后再测试一下好了，看看是浏览器哪一步出问题
> > > 
> > > 
> > > 你上面那个人xvfb-run nb run之后好像误打误撞的能用了，虽然还是有报错
> > 
> > 
> > 我试了一下你修改的chatgpt.py 正常nb run运行会报错 但是用xvfb-run nb run没报错
> 
> 我这个pr就是修报错但是能运行的，反正在Windows是正常的

windows是没问题，我也用了上面那个兄弟的方法xvfb-run nb run，还是会报错，整麻了，有空再研究研究

**Comment by zxczaq001** [comment]
> > > > 
> > > 
> > > 
> > > > > > 主要是我怀疑现在Ubuntu验证界面可能不一样，但是不关闭headless看看，也不知道是什么
> > > > > 
> > > > > 
> > > > > 我也觉得是验证界面不一样，但我们用的linux云服务器默认不带gui的，只有命令行，要用的话还要另外再装，而且运行gui比较耗资源。我有空在本地虚拟机上配置下linux环境然后再测试一下好了，看看是浏览器哪一步出问题
> > > > 
> > > > 
> > > > 你上面那个人xvfb-run nb run之后好像误打误撞的能用了，虽然还是有报错
> > > 
> > > 
> > > 我试了一下你修改的chatgpt.py 正常nb run运行会报错 但是用xvfb-run nb run没报错
> > 
> > 
> > 我这个pr就是修报错但是能运行的，反正在Windows是正常的
> 
> windows是没问题，我也用了上面那个兄弟的方法xvfb-run nb run，还是会报错，整麻了，有空再研究研究

能跑 但是只能在前台运行 我本来是用supervisord后台运行方便设置定时重启 现在只能用screen来跑

**Comment by coyude** [comment]
感谢大佬，腾讯云Ubuntu22.04下可以正常运行

**Comment by zsksmhq** [comment]
> 主要是我怀疑现在Ubuntu验证界面可能不一样，但是不关闭headless看看，也不知道是什么

我用的阿里云关了headless看了下，发现是他会一直进行人机验证，不管点了多少次都会再跳出验证按钮，但是用浏览器手动登录就不会这样，不知道为什么

**Comment by CCYellowStar** [comment]
> > 主要是我怀疑现在Ubuntu验证界面可能不一样，但是不关闭headless看看，也不知道是什么
> 
> 我用的阿里云关了headless看了下，发现是他会一直进行人机验证，不管点了多少次都会再跳出验证按钮，但是用浏览器手动登录就不会这样，不知道为什么

如果手动打开gpt网站的

**Comment by zsksmhq** [comment]
> > > 主要是我怀疑现在Ubuntu验证界面可能不一样，但是不关闭headless看看，也不知道是什么
> > 
> > 
> > 我用的阿里云关了headless看了下，发现是他会一直进行人机验证，不管点了多少次都会再跳出验证按钮，但是用浏览器手动登录就不会这样，不知道为什么
> 
> 如果手动打开gpt网站呢

手动打开没问题，然后我试了下挂梯子用bot就能正常登了

**Comment by CCYellowStar** [comment]
> > > > 主要是我怀疑现在Ubuntu验证界面可能不一样，但是不关闭headless看看，也不知道是什么
> > > 
> > > 
> > > 我用的阿里云关了headless看了下，发现是他会一直进行人机验证，不管点了多少次都会再跳出验证按钮，但是用浏览器手动登录就不会这样，不知道为什么
> > 
> > 
> > 如果手动打开gpt网站呢
> 
> 手动打开没问题，然后我试了下挂梯子用bot就能正常登了

貌似就是要挂梯子的

**Comment by zxczaq001** [comment]
> > > > > 主要是我怀疑现在Ubuntu验证界面可能不一样，但是不关闭headless看看，也不知道是什么
> > > > 
> > > > 
> > > > 我用的阿里云关了headless看了下，发现是他会一直进行人机验证，不管点了多少次都会再跳出验证按钮，但是用浏览器手动登录就不会这样，不知道为什么
> > > 
> > > 
> > > 如果手动打开gpt网站呢
> > 
> > 
> > 手动打开没问题，然后我试了下挂梯子用bot就能正常登了
> 
> 貌似就是要挂梯子的

我的日本服务器正常启动也不行

**Comment by CCYellowStar** [comment]
> image 之前还可以用 现在又开始了
我添加的更新加上了吗

**Pull request merged**
